services:
  website:
    build:
      context: .
    image: ghcr.io/runzhliu/welink/website:main
    container_name: welink-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/certs:ro
    restart: unless-stopped
    networks:
      - default
      - welink-net

networks:
  welink-net:
    external: true
